server:
  servlet:
    port: 8080
    contextPath: /api

spring:

  application:
    name: FoodOrderingApp-api

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/foodiesjunction           #IP Address and Port needs to be specified in the datasource URL.
    username: postgres
    password: postgres                                              #Password needs to be specified for datasource

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect